language: go

go:
  - 1.4
  - 1.5
  - 1.6

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

script:
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...
